---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name:  cs-deploy
  namespace: csns
  labels:
    app: cs
    name: cs-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs
      name: cs-po
  template: 
    metadata:
      name: cs-po
      namespace: csns
      labels:
        app: cs
        name: cs-po
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: cs-pvc
      containers:
      - name: cs-container
        image: lscr.io/linuxserver/code-server:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        envFrom:
        - configMapRef:
            name: cs-cm
        - secretRef:
            name: cs-secret
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: data-vol
          mountPath: /config/workspace
        # resources: 
        #   requests:
        #     memory: "256Mi"
        #     cpu: "200m"
        #   limits:
        #     memory: "256Mi"
        #     cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: cs-svc
  namespace: csns
  labels:
    app: cs-app
    name: cs-svc
spec:
  type: ClusterIP
  selector:
    app: cs
    name: cs-po
  ports:
  - port: 8443
    targetPort: 8443

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cs-ing
  namespace: csns
  labels:
    app: cs
    name: cs-ing
spec:
  ingressClassName: nginx
  rules:
  - host: cs.146.190.195.231.nip.io
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: cs-svc
            port:
              number: 8443