---
apiVersion: v1
kind: Namespace
metadata: 
  name: csns
  labels:
    app: cs
    name: csns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cs-cm
  namespace: csns
  labels:
    app: cs
    name: cs-cm
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code.146.190.195.231.nip.io
  # PUID: 0