---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name:  bggdb-deploy
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgg
      name: bggdb-po
  template: # This is a copy and paste from myns.yaml of the pod
    metadata:
      name: bggpod
      namespace: bggns # Will do to default if not written
      labels:
        app: bgg
        name: bggdb-po
    spec: 
      containers:
      - name: bggdb-pod-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    app: bgg
    name: bggdb-po
  ports:
  - port: 3306
    targetPort: 3306