---
apiVersion: v1
kind: Namespace
metadata: 
  name: mns
  labels:
    app: m
    name: mns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: m-cm
  namespace: mns
  labels:
    app: m
    name: m-cm
data:
  MINIO_ROOT_USER: user
  MINIO_DATA_DIR: /data
  MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
  MINIO_DISTRIBUTED_NODES: m-sts-0.m-hsvc.mns.svc.cluster.local,m-sts-1.m-hsvc.mns.svc.cluster.local,m-sts-2.m-hsvc.mns.svc.cluster.local,m-sts-3.m-hsvc.mns.svc.cluster.local
  MINIO_API_PORT_NUMBER: "9000"
  MINIO_CONSOLE_PORT_NUMBER: "9090"
